# This is a basic workflow to help you get started with Actions

name: Scriptable-Debugger-Pharo-Integration

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PHARO_CI_TESTING_ENVIRONMENT: 1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ Pharo-11 ]
  pull_request:
    branches: [ Pharo-11 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
        matrix:
          os: [ ubuntu-latest ]
          smalltalk: [ Pharo64-11 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2 # or 3
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Load Image and Run Release Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalk.release.ston
        timeout-minutes: 10
      - name: Clean Up
        run: rm -Rf ${{ env.SMALLTALK_CI_BUILD }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalk.all.ston
        timeout-minutes: 30
